### ISSUE TITLE
Missing data can cause incorrect calculations

### ISSUE THREAD

**Issue by badguy99** [badguy99/octocost#7]
No checks are done when multiplying usage by cost, they are just processed as a list so missing usage data can cause the usage to be multiplied by the wrong cost.

**Comment by davo1979** [comment]
Hi, sorry to post this here.. Is octocost still on HACS as I'm on the latest HACS 1.8.0 and octocost is not showing up in search. Also I'm not on the agile tarrif, will this still work for my normal tarrif? I have API code and region letter and serial etc.. 

Thanks.
