### ISSUE TITLE
Data Doesn't Match the octopus Website

### ISSUE THREAD

**Issue by dmelliott20** [badguy99/octocost#8]
The data pulling through doesn't match the data shown in the octopus my account usage. 

![image](https://user-images.githubusercontent.com/13154453/100223264-28c7d100-2f13-11eb-9097-6c889cd46c6e.png)

![image](https://user-images.githubusercontent.com/13154453/100223332-44cb7280-2f13-11eb-8ee7-e2c28183d4a5.png)

as a result the costs are also off, is it to do with timezones or DST?

**Comment by dmelliott20** [comment]
it could be missing the last half hour - my 23:30 - 00:00 usage was 0.592kwh

**Comment by badguy99** [comment]
That will be it, as that is when the day ends as far as SMETS2 smart meters are concerned from what I have read on https://forum.octopus.energy

Bit weird really, and it isn't noticed in summer, as the day ending at 23:30 utc is fine when that becomes 00:30 bst, but that is how it is
