### ISSUE TITLE
Octocost in HACS 

### ISSUE THREAD

**Issue by davo1979** [badguy99/octocost#9]
Hi, sorry to post this here.. Is octocost still on HACS as I'm on the latest HACS 1.8.0 and octocost is not showing up in search. Also I'm not on the agile tarrif, will this still work for my normal tarrif? I have API code and region letter and serial etc..

Thanks.

**Comment by badguy99** [comment]
It is still in HACS - I just double checked the repository list - https://github.com/hacs/default/blob/master/appdaemon
It only works for Agile octopus tariffs though - the base tariff is hard coded here - https://github.com/badguy99/octocost/blob/master/apps/octocost/octocost.py#L35 - you could always try forking the repository, changing it to suite your needs and installing it as a custom component in HACS from your fork.
